In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/CitySync DataSet/taxi_zone_lookup.csv')
df.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [ ]:
march_yellow = pd.read_parquet('/content/drive/MyDrive/CitySync DataSet/yellow_tripdata_2025-03.parquet')
march_yellow.tail()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
4145252,2,2025-03-31 23:10:10,2025-03-31 23:42:49,NaN,10.04,NaN,None,177,205,0,45.98,0.0,0.5,0.0,0.0,1.0,47.48,NaN,NaN,0.00
4145253,2,2025-03-31 23:14:47,2025-03-31 23:32:05,NaN,3.01,NaN,None,186,140,0,21.70,0.0,0.5,0.0,0.0,1.0,26.45,NaN,NaN,0.75
4145254,2,2025-03-31 23:18:16,2025-03-31 23:40:15,NaN,7.44,NaN,None,48,243,0,31.97,0.0,0.5,0.0,0.0,1.0,36.72,NaN,NaN,0.75
4145255,2,2025-03-31 23:30:16,2025-03-31 23:52:23,NaN,4.99,NaN,None,68,262,0,-4.75,0.0,0.5,0.0,0.0,1.0,6.14,NaN,NaN,0.75
4145256,2,2025-03-31 23:26:26,2025-03-31 23:48:30,NaN,9.88,NaN,None,144,42,0,42.06,0.0,0.5,0.0,0.0,1.0,46.81,NaN,NaN,0.75